export * as answer from "./answer.svg";
export * as check from "./check.svg";
export * as copy from "./copy.svg";
export * as deleteImg from "./delete.svg";
export * as emptyQuestions from "./empty-questions.svg";
export * as googleIcon from "./google-icon.svg";
export * as illustration from "./illustration.svg";
export * as like from "./like.svg";
export * as logo from "./logo.svg";
